### ISSUE TITLE
manager login

### ISSUE THREAD

**Issue by HusainSuksar** [AshiqurRahaman02/zarektronix#1]
when i try to sign up as manager role it give alert : The string did not match the expected pattern. 
why is that??

**Comment by AshiqurRahaman02** [comment]
Thank you for bringing this signup issue to my attention. However, I want to inform you that it's working perfectly fine on all of my devices. 

If you could provide a snapshot or screenshot of the error message you're encountering, it would greatly assist me in identifying the issue and providing a solution. 

Additionally, if you'd like to try out the demo manager account, here are the details: 
Email: manager@gmail.com 
Password: manager 

Feel free to test it out and let me know if you need further assistance.

**Comment by HusainSuksar** [comment]
i am trying it on local device, 
<img width="1099" alt="Screenshot 2024-03-18 at 9 00 21 PM" src="https://github.com/AshiqurRahaman02/zarektronix/assets/67893172/53ac027d-b6ed-455d-9822-818deae82174">

**Comment by HusainSuksar** [comment]
i was looking for this kinda web application , you did a great job, 

also if i want to host the same web application with some additional touch, how can i do that?? Do the Git repo has all the files needed?
2) how do i logout?? there is no button. or code for logout

**Comment by AshiqurRahaman02** [comment]
Thank you for your kind words regarding the web application. 

Indeed, the Git repository contains all the necessary files for the client-side functionality. If you intend to incorporate additional server-side features, you can refer to the repository mentioned in the README for the relevant codebase. 

Regarding the logout functionality, I must acknowledge that it hasn't been implemented yet. I'll take note of this suggestion for future updates. 

If you find that your issue has been adequately addressed, I kindly request you to close this issue with a suitable comment. 

Thank you once again for your feedback and assistance.

**Comment by HusainSuksar** [comment]
okay thanks for your time and help. All the best for future projects.
